title: "نام برند شما"
description: "توضیحات کوتاه درباره سایت"
baseurl: ""
url: "https://نام_کاربری.github.io"
permalink: /blog/:title/
theme: null
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
author: "نام شما"
email: "ایمیل شما"
