title: "IRSPEEDY"
description: "سایت خرید اکانت اصلی IRSPEEDY"
baseurl: ""
url: "https://irspeedy.github.io"
permalink: /blog/:title/
theme: null
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
author: "IRSPEEDY"
email: "info@irspeedy.store"
